/**
 * Every Discord.js v14 guild event this bot actually listens to.
 * Keys are English identifiers used in SQLite, slash commands, and env overrides.
 * Groups map to /log group subcommands.
 */
const COLORS = {
  create: 0x57f287,
  update: 0xfee75c,
  delete: 0xed4245,
  voice: 0x5865f2,
  member: 0xeb459e,
  mod: 0xf26522,
  info: 0x5865f2,
};

const EVENTS = [
  { key: "messageDelete", group: "message", color: "delete", audit: false, partials: true },
  { key: "messageUpdate", group: "message", color: "update", audit: false, partials: true },
  { key: "messageDeleteBulk", group: "message", color: "delete", audit: false },
  { key: "messageReactionAdd", group: "message", color: "create", audit: false, partials: true },
  { key: "messageReactionRemove", group: "message", color: "delete", audit: false, partials: true },
  { key: "messageReactionRemoveAll", group: "message", color: "delete", audit: false },
  { key: "messageReactionRemoveEmoji", group: "message", color: "delete", audit: false },
  { key: "messagePin", group: "message", color: "update", audit: true },
  { key: "messageUnpin", group: "message", color: "update", audit: true },
  { key: "guildMemberAdd", group: "member", color: "create", audit: false },
  { key: "guildMemberRemove", group: "member", color: "delete", audit: true },
  { key: "guildMemberUpdate", group: "member", color: "update", audit: true },
  { key: "guildBanAdd", group: "moderation", color: "mod", audit: true },
  { key: "guildBanRemove", group: "moderation", color: "mod", audit: true },
  { key: "inviteCreate", group: "invite", color: "create", audit: true },
  { key: "inviteDelete", group: "invite", color: "delete", audit: true },
  { key: "channelCreate", group: "channel", color: "create", audit: true },
  { key: "channelDelete", group: "channel", color: "delete", audit: true },
  { key: "channelUpdate", group: "channel", color: "update", audit: true },
  { key: "channelPinsUpdate", group: "channel", color: "update", audit: false },
  { key: "threadCreate", group: "thread", color: "create", audit: true },
  { key: "threadDelete", group: "thread", color: "delete", audit: true },
  { key: "threadUpdate", group: "thread", color: "update", audit: true },
  { key: "threadMembersUpdate", group: "thread", color: "update", audit: false },
  { key: "threadListSync", group: "thread", color: "info", audit: false },
  { key: "roleCreate", group: "role", color: "create", audit: true },
  { key: "roleDelete", group: "role", color: "delete", audit: true },
  { key: "roleUpdate", group: "role", color: "update", audit: true },
  { key: "emojiCreate", group: "emoji", color: "create", audit: true },
  { key: "emojiDelete", group: "emoji", color: "delete", audit: true },
  { key: "emojiUpdate", group: "emoji", color: "update", audit: true },
  { key: "stickerCreate", group: "sticker", color: "create", audit: true },
  { key: "stickerDelete", group: "sticker", color: "delete", audit: true },
  { key: "stickerUpdate", group: "sticker", color: "update", audit: true },
  { key: "voiceJoin", group: "voice", color: "voice", audit: false },
  { key: "voiceLeave", group: "voice", color: "voice", audit: false },
  { key: "voiceMove", group: "voice", color: "voice", audit: false },
  { key: "voiceServerMute", group: "voice", color: "mod", audit: true },
  { key: "voiceServerDeafen", group: "voice", color: "mod", audit: true },
  { key: "voiceStream", group: "voice", color: "voice", audit: false },
  { key: "voiceVideo", group: "voice", color: "voice", audit: false },
  { key: "stageInstanceCreate", group: "stage", color: "create", audit: true },
  { key: "stageInstanceDelete", group: "stage", color: "delete", audit: true },
  { key: "stageInstanceUpdate", group: "stage", color: "update", audit: true },
  { key: "guildUpdate", group: "server", color: "update", audit: true },
  { key: "webhookUpdate", group: "webhook", color: "update", audit: true },
  { key: "guildIntegrationsUpdate", group: "integration", color: "update", audit: true },
  { key: "guildScheduledEventCreate", group: "event", color: "create", audit: true },
  { key: "guildScheduledEventDelete", group: "event", color: "delete", audit: true },
  { key: "guildScheduledEventUpdate", group: "event", color: "update", audit: true },
  { key: "guildScheduledEventUserAdd", group: "event", color: "create", audit: false },
  { key: "guildScheduledEventUserRemove", group: "event", color: "delete", audit: false },
  { key: "autoModerationRuleCreate", group: "automod", color: "create", audit: true },
  { key: "autoModerationRuleDelete", group: "automod", color: "delete", audit: true },
  { key: "autoModerationRuleUpdate", group: "automod", color: "update", audit: true },
  { key: "autoModerationActionExecution", group: "automod", color: "mod", audit: false },
  { key: "applicationCommandPermissionsUpdate", group: "command", color: "update", audit: false },
  { key: "guildAuditLogEntryCreate", group: "audit", color: "mod", audit: false },
  { key: "presenceUpdate", group: "presence", color: "info", audit: false, defaultOff: true },
  { key: "userUpdate", group: "user", color: "info", audit: false, defaultOff: true },
  { key: "guildMemberTimeout", group: "moderation", color: "mod", audit: true },
  { key: "guildMemberNickname", group: "member", color: "update", audit: true },
  { key: "guildMemberAvatar", group: "member", color: "update", audit: false },
  { key: "guildMemberRoles", group: "member", color: "update", audit: true },
  { key: "guildMemberBoost", group: "member", color: "create", audit: false },
  { key: "guildBoostLevel", group: "server", color: "create", audit: false },
  { key: "messageCreate", group: "message", color: "create", audit: false, defaultOff: true },
  { key: "typingStart", group: "typing", color: "info", audit: false, defaultOff: true },
  { key: "messagePollVoteAdd", group: "poll", color: "create", audit: false },
  { key: "messagePollVoteRemove", group: "poll", color: "delete", audit: false },
  { key: "voiceChannelEffect", group: "voice", color: "voice", audit: false },
  { key: "voiceSelfMute", group: "voice", color: "voice", audit: false, defaultOff: true },
  { key: "voiceSelfDeaf", group: "voice", color: "voice", audit: false, defaultOff: true },
  { key: "voiceSuppress", group: "voice", color: "voice", audit: false },
  { key: "threadMemberUpdate", group: "thread", color: "update", audit: false },
  { key: "soundboardCreate", group: "soundboard", color: "create", audit: true },
  { key: "soundboardDelete", group: "soundboard", color: "delete", audit: true },
  { key: "soundboardUpdate", group: "soundboard", color: "update", audit: true },
  { key: "entitlementCreate", group: "monetization", color: "create", audit: false },
  { key: "entitlementUpdate", group: "monetization", color: "update", audit: false },
  { key: "entitlementDelete", group: "monetization", color: "delete", audit: false },
  { key: "subscriptionCreate", group: "monetization", color: "create", audit: false },
  { key: "subscriptionUpdate", group: "monetization", color: "update", audit: false },
  { key: "subscriptionDelete", group: "monetization", color: "delete", audit: false },
  { key: "commandUse", group: "command", color: "info", audit: false, defaultOff: true },
  { key: "guildAvailable", group: "server", color: "info", audit: false, defaultOff: true },
  { key: "guildUnavailable", group: "server", color: "delete", audit: false },
  { key: "guildMemberPending", group: "member", color: "update", audit: false },
];

const GROUPS = [...new Set(EVENTS.map((e) => e.group))];

const byKey = Object.fromEntries(EVENTS.map((e) => [e.key, e]));

module.exports = { EVENTS, GROUPS, COLORS, byKey };
